import type { IconType } from "react-icons";
import {
  LuActivity,
  LuCircleAlert,
  LuTriangleAlert,
  LuArrowLeft,
  LuArrowRight,
  LuBell,
  LuCalendar,
  LuCheck,
  LuCircleCheck,
  LuCircleCheckBig,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuChevronUp,
  LuChevronsUpDown,
  LuCircle,
  LuClock,
  LuCloud,
  LuCpu,
  LuDatabase,
  LuDot,
  LuDownload,
  LuExternalLink,
  LuEye,
  LuEyeOff,
  LuFileAudio,
  LuFileText,
  LuFilter,
  LuFolder,
  LuFolderOpen,
  LuFolderTree,
  LuForward,
  LuGripVertical,
  LuHardDrive,
  LuCircleHelp,
  LuImage,
  LuInbox,
  LuInfo,
  LuLayoutDashboard,
  LuLink,
  LuLink2,
  LuLoaderCircle,
  LuLock,
  LuLogOut,
  LuMail,
  LuMenu,
  LuMessageCircle,
  LuEllipsis,
  LuPanelLeft,
  LuPlus,
  LuRefreshCw,
  LuRotateCcw,
  LuSave,
  LuScrollText,
  LuSearch,
  LuSend,
  LuServer,
  LuSettings,
  LuSettings2,
  LuShield,
  LuShieldX,
  LuTimer,
  LuTrash2,
  LuTrendingUp,
  LuUser,
  LuUserCheck,
  LuUsers,
  LuVideo,
  LuX,
  LuCircleX,
  LuZap,
} from "react-icons/lu";

export type LucideIcon = IconType;

export {
  LuActivity as Activity,
  LuCircleAlert as AlertCircle,
  LuTriangleAlert as AlertTriangle,
  LuArrowLeft as ArrowLeft,
  LuArrowRight as ArrowRight,
  LuBell as Bell,
  LuCalendar as Calendar,
  LuCheck as Check,
  LuCircleCheck as CheckCircle,
  LuCircleCheckBig as CheckCircle2,
  LuChevronDown as ChevronDown,
  LuChevronLeft as ChevronLeft,
  LuChevronRight as ChevronRight,
  LuChevronUp as ChevronUp,
  LuChevronsUpDown as ChevronsUpDown,
  LuCircle as Circle,
  LuClock as Clock,
  LuCloud as Cloud,
  LuCpu as Cpu,
  LuDatabase as Database,
  LuDot as Dot,
  LuDownload as Download,
  LuExternalLink as ExternalLink,
  LuEye as Eye,
  LuEyeOff as EyeOff,
  LuFileAudio as FileAudio,
  LuFileText as FileText,
  LuFilter as Filter,
  LuFolder as Folder,
  LuFolderOpen as FolderOpen,
  LuFolderTree as FolderTree,
  LuForward as Forward,
  LuGripVertical as GripVertical,
  LuHardDrive as HardDrive,
  LuCircleHelp as HelpCircle,
  LuImage as Image,
  LuInbox as Inbox,
  LuInfo as Info,
  LuLayoutDashboard as LayoutDashboard,
  LuLink as Link,
  LuLink2 as Link2,
  LuLoaderCircle as Loader2,
  LuLock as Lock,
  LuLogOut as LogOut,
  LuMail as Mail,
  LuMenu as Menu,
  LuMessageCircle as MessageCircle,
  LuEllipsis as MoreHorizontal,
  LuPanelLeft as PanelLeft,
  LuPlus as Plus,
  LuRefreshCw as RefreshCw,
  LuRotateCcw as RotateCcw,
  LuSave as Save,
  LuScrollText as ScrollText,
  LuSearch as Search,
  LuSend as Send,
  LuServer as Server,
  LuSettings as Settings,
  LuSettings2 as Settings2,
  LuShield as Shield,
  LuShieldX as ShieldX,
  LuTimer as Timer,
  LuTrash2 as Trash2,
  LuTrendingUp as TrendingUp,
  LuUser as User,
  LuUserCheck as UserCheck,
  LuUsers as Users,
  LuVideo as Video,
  LuX as X,
  LuCircleX as XCircle,
  LuZap as Zap,
};
