import type { IconType } from "react-icons";
import {
  LuActivity,
  LuAlertCircle,
  LuAlertTriangle,
  LuArrowLeft,
  LuArrowRight,
  LuCalendar,
  LuCheck,
  LuCheckCircle,
  LuCircleCheckBig,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuChevronUp,
  LuChevronsUpDown,
  LuCircle,
  LuClock,
  LuCloud,
  LuCpu,
  LuDatabase,
  LuDot,
  LuExternalLink,
  LuEye,
  LuEyeOff,
  LuFileAudio,
  LuFileText,
  LuFilter,
  LuFolder,
  LuFolderOpen,
  LuFolderTree,
  LuForward,
  LuGripVertical,
  LuHardDrive,
  LuCircleHelp,
  LuImage,
  LuInbox,
  LuLayoutDashboard,
  LuLink,
  LuLink2,
  LuLoaderCircle,
  LuLock,
  LuLogOut,
  LuMail,
  LuMenu,
  LuMessageCircle,
  LuMessageSquare,
  LuMoreHorizontal,
  LuPanelLeft,
  LuPlus,
  LuRefreshCw,
  LuRotateCcw,
  LuSave,
  LuScrollText,
  LuSearch,
  LuSend,
  LuServer,
  LuSettings,
  LuSettings2,
  LuShield,
  LuShieldX,
  LuTrash2,
  LuUser,
  LuUserCheck,
  LuUsers,
  LuVideo,
  LuX,
  LuXCircle,
  LuZap,
} from "react-icons/lu";

export type LucideIcon = IconType;

export {
  LuActivity as Activity,
  LuAlertCircle as AlertCircle,
  LuAlertTriangle as AlertTriangle,
  LuArrowLeft as ArrowLeft,
  LuArrowRight as ArrowRight,
  LuCalendar as Calendar,
  LuCheck as Check,
  LuCheckCircle as CheckCircle,
  LuCircleCheckBig as CheckCircle2,
  LuChevronDown as ChevronDown,
  LuChevronLeft as ChevronLeft,
  LuChevronRight as ChevronRight,
  LuChevronUp as ChevronUp,
  LuChevronsUpDown as ChevronsUpDown,
  LuCircle as Circle,
  LuClock as Clock,
  LuCloud as Cloud,
  LuCpu as Cpu,
  LuDatabase as Database,
  LuDot as Dot,
  LuExternalLink as ExternalLink,
  LuEye as Eye,
  LuEyeOff as EyeOff,
  LuFileAudio as FileAudio,
  LuFileText as FileText,
  LuFilter as Filter,
  LuFolder as Folder,
  LuFolderOpen as FolderOpen,
  LuFolderTree as FolderTree,
  LuForward as Forward,
  LuGripVertical as GripVertical,
  LuHardDrive as HardDrive,
  LuCircleHelp as HelpCircle,
  LuImage as Image,
  LuInbox as Inbox,
  LuLayoutDashboard as LayoutDashboard,
  LuLink as Link,
  LuLink2 as Link2,
  LuLoaderCircle as Loader2,
  LuLock as Lock,
  LuLogOut as LogOut,
  LuMail as Mail,
  LuMenu as Menu,
  LuMessageCircle as MessageCircle,
  LuMessageSquare as MessageSquare,
  LuMoreHorizontal as MoreHorizontal,
  LuPanelLeft as PanelLeft,
  LuPlus as Plus,
  LuRefreshCw as RefreshCw,
  LuRotateCcw as RotateCcw,
  LuSave as Save,
  LuScrollText as ScrollText,
  LuSearch as Search,
  LuSend as Send,
  LuServer as Server,
  LuSettings as Settings,
  LuSettings2 as Settings2,
  LuShield as Shield,
  LuShieldX as ShieldX,
  LuTrash2 as Trash2,
  LuUser as User,
  LuUserCheck as UserCheck,
  LuUsers as Users,
  LuVideo as Video,
  LuX as X,
  LuXCircle as XCircle,
  LuZap as Zap,
};
